# CIS Kubernetes Benchmark Compliance Checks
# Based on CIS Kubernetes V1.8.0 Benchmark

apiVersion: v1
kind: ConfigMap
metadata:
  name: cis-kubernetes-benchmark
  namespace: security
data:
  # Control Plane Components

  1.1.1: |
    # API server pod specification file permissions
    Check: stat -c %a /etc/kubernetes/manifests/kube-apiserver.yaml
    Expected: 644 or more restrictive

  1.1.2: |
    # API server pod specification file ownership
    Check: stat -c %U:%G /etc/kubernetes/manifests/kube-apiserver.yaml
    Expected: root:root

  1.2.1: |
    # Ensure that the --anonymous-auth argument is set to false
    Check: ps -ef | grep kube-apiserver | grep anonymous-auth
    Expected: --anonymous-auth=false

  1.2.2: |
    # Ensure that the --token-auth-file parameter is not set
    Check: ps -ef | grep kube-apiserver | grep token-auth-file
    Expected: Not set

  1.2.3: |
    # Ensure that the --DenyServiceExternalIPs is not set
    Check: ps -ef | grep kube-apiserver | grep DenyServiceExternalIPs
    Expected: Should not be present

  1.2.5: |
    # Ensure that the --kubelet-client-certificate argument is set
    Check: ps -ef | grep kube-apiserver | grep kubelet-client-certificate
    Expected: Set appropriately

  1.2.6: |
    # Ensure that the --kubelet-client-key argument is set
    Check: ps -ef | grep kube-apiserver | grep kubelet-client-key
    Expected: Set appropriately

  1.2.7: |
    # Ensure that the --authorization-mode argument includes Node
    Check: ps -ef | grep kube-apiserver | grep authorization-mode
    Expected: Includes 'Node'

  1.2.8: |
    # Ensure that the --authorization-mode argument includes RBAC
    Check: ps -ef | grep kube-apiserver | grep authorization-mode
    Expected: Includes 'RBAC'

  1.2.15: |
    # Ensure that the --audit-log-path argument is set
    Check: ps -ef | grep kube-apiserver | grep audit-log-path
    Expected: Set appropriately

  1.2.18: |
    # Ensure that the --insecure-bind-address argument is not set
    Check: ps -ef | grep kube-apiserver | grep insecure-bind-address
    Expected: Not set

  1.2.19: |
    # Ensure that the --insecure-port argument is set to 0
    Check: ps -ef | grep kube-apiserver | grep insecure-port
    Expected: --insecure-port=0

  1.2.20: |
    # Ensure that the --secure-port argument is not set to 0
    Check: ps -ef | grep kube-apiserver | grep secure-port
    Expected: Not 0 (or not set, defaults to 6443)

  1.2.22: |
    # Ensure that the --encryption-provider-config argument is set
    Check: ps -ef | grep kube-apiserver | grep encryption-provider-config
    Expected: Set appropriately

  1.3.2: |
    # Ensure that the --profiling argument is set to false
    Check: ps -ef | grep kube-controller-manager | grep profiling
    Expected: --profiling=false

  1.3.6: |
    # Ensure that the RotateKubeletServerCertificate is set to true
    Check: ps -ef | grep kube-controller-manager | grep RotateKubeletServerCertificate
    Expected: RotateKubeletServerCertificate=true

  1.4.1: |
    # Ensure that the --profiling argument is set to false (scheduler)
    Check: ps -ef | grep kube-scheduler | grep profiling
    Expected: --profiling=false

  # etcd

  2.1: |
    # Ensure that the --cert-file and --key-file arguments are set
    Check: ps -ef | grep etcd | grep -E 'cert-file|key-file'
    Expected: Both set appropriately

  2.2: |
    # Ensure that the --client-cert-auth argument is set to true
    Check: ps -ef | grep etcd | grep client-cert-auth
    Expected: --client-cert-auth=true

  2.3: |
    # Ensure that the --auto-tls argument is not set to true
    Check: ps -ef | grep etcd | grep auto-tls
    Expected: Not true

  2.4: |
    # Ensure that the --peer-cert-file and --peer-key-file arguments are set
    Check: ps -ef | grep etcd | grep -E 'peer-cert-file|peer-key-file'
    Expected: Both set appropriately

  2.7: |
    # Ensure that a unique Certificate Authority is used for etcd
    Check: Compare etcd CA with Kubernetes CA
    Expected: Different CA certificates

  # Worker Node Configuration

  4.2.1: |
    # Ensure that the --anonymous-auth argument is set to false (kubelet)
    Check: ps -ef | grep kubelet | grep anonymous-auth
    Expected: --anonymous-auth=false

  4.2.2: |
    # Ensure that the --authorization-mode argument is not set to AlwaysAllow
    Check: ps -ef | grep kubelet | grep authorization-mode
    Expected: Not 'AlwaysAllow'

  4.2.3: |
    # Ensure that the --client-ca-file argument is set
    Check: ps -ef | grep kubelet | grep client-ca-file
    Expected: Set appropriately

  4.2.6: |
    # Ensure that the --protect-kernel-defaults argument is set to true
    Check: ps -ef | grep kubelet | grep protect-kernel-defaults
    Expected: --protect-kernel-defaults=true

  4.2.10: |
    # Ensure that the --tls-cert-file and --tls-private-key-file arguments are set
    Check: ps -ef | grep kubelet | grep -E 'tls-cert-file|tls-private-key-file'
    Expected: Both set appropriately

  # Policies

  5.1.3: |
    # Ensure that the controller manager pod specification file has permissions of 644
    Check: stat -c %a /etc/kubernetes/manifests/kube-controller-manager.yaml
    Expected: 644 or more restrictive

  5.2.1: |
    # Minimize the admission of privileged containers
    Check: kubectl get psp -o json | jq '.items[] | select(.spec.privileged==true)'
    Expected: No privileged PSPs or only for specific namespaces

  5.2.2: |
    # Minimize the admission of containers wishing to share the host process ID namespace
    Check: kubectl get psp -o json | jq '.items[] | select(.spec.hostPID==true)'
    Expected: No PSPs allowing hostPID

  5.2.3: |
    # Minimize the admission of containers wishing to share the host IPC namespace
    Check: kubectl get psp -o json | jq '.items[] | select(.spec.hostIPC==true)'
    Expected: No PSPs allowing hostIPC

  5.2.4: |
    # Minimize the admission of containers wishing to share the host network namespace
    Check: kubectl get psp -o json | jq '.items[] | select(.spec.hostNetwork==true)'
    Expected: No PSPs allowing hostNetwork

  5.2.5: |
    # Minimize the admission of containers with allowPrivilegeEscalation
    Check: kubectl get psp -o json | jq '.items[] | select(.spec.allowPrivilegeEscalation==true)'
    Expected: Minimal or controlled usage

  5.3.1: |
    # Ensure that the CNI in use supports Network Policies
    Check: kubectl get pods -n kube-system | grep -i network
    Expected: Network policy supporting CNI

  5.3.2: |
    # Ensure that all Namespaces have Network Policies defined
    Check: kubectl get networkpolicies --all-namespaces
    Expected: Each namespace should have NetworkPolicies

  5.4.1: |
    # Prefer using secrets as files over secrets as environment variables
    Check: kubectl get pods --all-namespaces -o json | jq '.items[] | select(.spec.containers[].env[]?.valueFrom.secretKeyRef)'
    Expected: Minimal usage

  5.7.1: |
    # Create administrative boundaries between resources using namespaces
    Check: kubectl get namespaces
    Expected: Proper namespace segmentation

  5.7.2: |
    # Ensure that the seccomp profile is set to docker/default
    Check: kubectl get pods --all-namespaces -o json | jq '.items[] | .metadata.annotations."seccomp.security.alpha.kubernetes.io/pod"'
    Expected: runtime/default or docker/default

  5.7.3: |
    # Apply Security Context to Your Pods and Containers
    Check: kubectl get pods --all-namespaces -o json | jq '.items[] | select(.spec.securityContext==null)'
    Expected: All pods should have securityContext

  5.7.4: |
    # Do not use the default service account
    Check: kubectl get pods --all-namespaces -o json | jq '.items[] | select(.spec.serviceAccountName=="default")'
    Expected: Pods should use dedicated service accounts
